### ISSUE TITLE
NPE while standing still

### ISSUE THREAD

**Issue by SlimeDog** [kicjow/Block-Particles#3]
Spigot 1.11.2 latest
BlockParticles 1.9.6

Only one player online (me); this is a dev server. I was AFK at the indicated time.

> [17:18:28 WARN]: [BlockParticles] Plugin BlockParticles v1.9.6 generated an exception while executing task 87
java.lang.NullPointerException
        at me.badbones69.blockparticles.MCUpdate.report(MCUpdate.java:144) ~[?:?]
        at me.badbones69.blockparticles.MCUpdate.lambda$0(MCUpdate.java:66) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar-2017-05-05-1401:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.11.2.jar-2017-05-05-1401:git-Spigot-3fb9445-2b6c9f4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by kicjow** [comment]
Thanks, it was just a random error because it couldn't get a message from McUpdate.org. Ill make sure to suppress that error.

**Comment by SlimeDog** [comment]
Thanks.
