### ISSUE TITLE
exception during startup in 1.12

### ISSUE THREAD

**Issue by smmmadden** [kicjow/Block-Particles#4]
[23:52:56] [Craft Scheduler Thread - 231/WARN]: [BlockParticles] Plugin BlockParticles v1.9.6 generated an exception while executing task 23
java.lang.NullPointerException: null
	at me.badbones69.blockparticles.MCUpdate.report(MCUpdate.java:144) ~[?:?]
	at me.badbones69.blockparticles.MCUpdate.lambda$0(MCUpdate.java:66) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_131]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

It's the last thing that loads and throws the above - haven't logged in yet.
BungeeCord Server 1.12
Spigot Servers 1.12
BlockParticles 1.9.6
O/S Windows 10 Professional x64

**Comment by kicjow** [comment]
It is fixed in the newest update.
